# Site settings
title:       Robotics & Artificial Intelligence
email:       rohithrnair@outlook.com
author:      codeslord
description: "Creating the future isn't Magic. It's Artificial Intelligence"
baseurl:     ""
url:         "http://codeslord.github.io"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - contact.html

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: G-0EB3HP6PBH
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
enable_mermaid: true
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: codeslord
reddit_username:
bitbucket_username:
stackoverflow_id: codeslord
twitter_username: rohithrnair
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: rohithrnair
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false
#buy me a coffee
show_buymeacoffee: false
buymeacoffee_username: rohithrnair

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'If you found this post helpful, please consider sharing it with your network!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
kramdown:
  math_engine: katex
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: true
    #   start_line: 1
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     8
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
